# Jekyll configuration file

# site settings
title: Slides
description: Slides for my talks.
url: https://juseg.dev
baseurl: /slides
future: true

# build settings
collections:
  talks:
    output: true
    permalink: /:slug/
